name: Deploy Dev API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # Uses your self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop existing containers
        run: make clean

      - name: Build and start new containers
        run: make

      - name: Verify Running Containers
        run: docker ps
