volumes:
  cache:
    driver: local
  database:
    name: database

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    env_file:
      - .env
    networks:
      - network
    ports:
      - ${MONGO_EXTERNAL_PORT}:${MONGO_INTERNAL_PORT}
    volumes:
      - database:/data/db

  calenduh-api:
    container_name: calenduh-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - network
    ports:
      - "8080:8080"
    volumes:
      - cache:/var/lib/cache
    depends_on:
      - mongo

networks:
  network:
    driver: bridge