name: Deploy API to Docker Hub and Beast - Production

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Copy repository to the desired location
      - name: Load Repository
        run: |
          cp -r ${{ github.workspace }} /home/kaden/calenduh/${{ github.ref_name }}

      # Copy .env file to the branch directory
      - name: Load Environment Variables
        run: |
          cp /home/kaden/calenduh/.env /home/kaden/calenduh/${{ github.ref_name }}

      # Change working directory to /home/kaden/calenduh/main
      - name: Clean
        working-directory: /home/kaden/calenduh/${{ github.ref_name }}
        run: |
          make clean   # Clean up

      # Optional: Pull Image and Start Container
      - name: Build & Run
        working-directory: /home/kaden/calenduh/${{ github.ref_name }}
        run: |
          make