name: Deploy API

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Load Environment Variables
      - name: Load Environment Variables
        run: |
          cp /home/kaden/calenduh/.env .

      # Login To Docker
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calenduh:backend

      # Clean Up Environment Variables
      - name: Load Configuration and Clean up Environment Variables
        run: |
          cp .env /home/kaden/calenduh/${{ github.ref_name }}
          cp docker-compose.yml /home/kaden/calenduh/${{ github.ref_name }}
          rm .env

      # Run Docker Image
      - name: Run Docker Image
        working-directory: /home/kaden/calenduh/${{ github.ref_name }}
        run: |
          docker compose down calenduh-api || true
          docker compose up calenduh-api -d
