name: Deploy API

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login To Docker
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build Docker Image
      - name: Build Docker Image
        uses: docker/setup-buildx-action@v3

      # Push Docker Image
      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calenduh:backend
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Pull Docker Image
      - name: Pull Docker Image
        working-directory: /home/kaden/calenduh/${{ github.ref_name }}
        run: |
          cp ../.env .
          docker pull ${{ secrets.DOCKER_USERNAME }}/calenduh:backend
          docker compose down calenduh-api
          docker compose up calenduh-api -d