name: Deploy API

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Load Environment Variables
      - name: Load Environment Variables
        run: |
          cp /home/kaden/calenduh/.env .

      # Compile SQL Queries
      - name: Compile SQL Queries
        run: |
          make sqlc

      # Login To Docker
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Build and Push Docker Image
      - name: Build and Run Docker Image
        run: |
          make build
          make stop
          make run

      # Clean up Docker Resources
      - name: Clean up Docker resources
        run: |
          docker system prune
          docker builder prune
