name: Deploy API

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Load Environment Variables
      - name: Load Environment Variables
        run: |
          cp /home/kaden/calenduh/.env .

      # Login To Docker
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Push Docker Image
      - name: Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calenduh:backend
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/calenduh:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/calenduh:cache,mode=push



      # Clean Up Environment Variables
      - name: Clean Up Environment Variables
        run: |
          rm .env

      # Pull Docker Image
      - name: Pull Docker Image
        working-directory: /home/kaden/calenduh/${{ github.ref_name }}
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/calenduh:backend
          docker compose down calenduh-api
          docker compose up calenduh-api -d